version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install  # or any other package manager

  build:
    commands:
      - echo Building the project...
      - NODE_OPTIONS="--max-old-space-size=4096" npm run build  # Increase memory limit # Your build command

artifacts:
  files:
    - '**/*'
  base-directory: build/  # This should point to your output directory
