version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install  # or any other package manager

  build:
    commands:
      - echo Building the project...
      - npm run build  # Your build command

artifacts:
  files:
    - '**/*'
  base-directory: build/  # This should point to your output directory
